### ISSUE TITLE
master下载部署后，界面菜单不显示

### ISSUE THREAD

**Issue by fengshengchang** [Joyboo/Joyboo-vben-admin-thin#1]
master下载部署后，界面菜单不显示，请教下是哪里问题？

![image](https://user-images.githubusercontent.com/14884481/208559203-9c0dd492-445a-46f9-87ec-f72057f9d3a2.png)

**Comment by Joyboo** [comment]
感觉是动态路由没有注册成功，如果不知道如何排查，可联系我 邮箱 joyboo666@gmail.com
